# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, confloat, constr


class WorkflowDetails(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str = Field(..., title="Workflow Name")
    description: str | None = Field("", title="Workflow Description")


class NormalizeAttrs(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    skip_if_not_exists: bool | None = Field(
        True,
        description="Skip if the column does not exist.",
        title="Skip If Not Exists",
    )
    sort_columns: bool | None = Field(
        True, description="Sort new columns alphabetically.", title="Sort Columns"
    )


class FeaturedList(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    vars: list[str] = Field(..., title="")


class Url(str, Enum):
    https___tile_openstreetmap_org__z___x___y__png = (
        "https://tile.openstreetmap.org/{z}/{x}/{y}.png"
    )


class BaseMaps(BaseModel):
    url: Literal["https://tile.openstreetmap.org/{z}/{x}/{y}.png"] = Field(
        "https://tile.openstreetmap.org/{z}/{x}/{y}.png", title="Preset Layer URL"
    )
    opacity: confloat(ge=0.0, le=1.0) | None = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class Url1(str, Enum):
    https___server_arcgisonline_com_ArcGIS_rest_services_World_Street_Map_MapServer_tile__z___y___x_ = "https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}"


class BaseMaps1(BaseModel):
    url: Literal[
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}"
    ] = Field(
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}",
        title="Preset Layer URL",
    )
    opacity: confloat(ge=0.0, le=1.0) | None = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class Url2(str, Enum):
    https___server_arcgisonline_com_ArcGIS_rest_services_World_Imagery_MapServer_tile__z___y___x_ = "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}"


class BaseMaps2(BaseModel):
    url: Literal[
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}"
    ] = Field(
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",
        title="Preset Layer URL",
    )
    opacity: confloat(ge=0.0, le=1.0) | None = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class Url3(str, Enum):
    https___server_arcgisonline_com_ArcGIS_rest_services_World_Topo_Map_MapServer_tile__z___y___x_ = "https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}"


class BaseMaps3(BaseModel):
    url: Literal[
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}"
    ] = Field(
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}",
        title="Preset Layer URL",
    )
    opacity: confloat(ge=0.0, le=1.0) | None = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class Url4(str, Enum):
    https___tiles_arcgis_com_tiles_POUcpLYXNckpLjnY_arcgis_rest_services_landDx_basemap_tiles_mapservice_MapServer_tile__z___y___x_ = "https://tiles.arcgis.com/tiles/POUcpLYXNckpLjnY/arcgis/rest/services/landDx_basemap_tiles_mapservice/MapServer/tile/{z}/{y}/{x}"


class BaseMaps4(BaseModel):
    url: Literal[
        "https://tiles.arcgis.com/tiles/POUcpLYXNckpLjnY/arcgis/rest/services/landDx_basemap_tiles_mapservice/MapServer/tile/{z}/{y}/{x}"
    ] = Field(
        "https://tiles.arcgis.com/tiles/POUcpLYXNckpLjnY/arcgis/rest/services/landDx_basemap_tiles_mapservice/MapServer/tile/{z}/{y}/{x}",
        title="Preset Layer URL",
    )
    opacity: confloat(ge=0.0, le=1.0) | None = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class Url5(str, Enum):
    https___server_arcgisonline_com_arcgis_rest_services_Elevation_World_Hillshade_MapServer_tile__z___y___x_ = "https://server.arcgisonline.com/arcgis/rest/services/Elevation/World_Hillshade/MapServer/tile/{z}/{y}/{x}"


class BaseMaps5(BaseModel):
    url: Literal[
        "https://server.arcgisonline.com/arcgis/rest/services/Elevation/World_Hillshade/MapServer/tile/{z}/{y}/{x}"
    ] = Field(
        "https://server.arcgisonline.com/arcgis/rest/services/Elevation/World_Hillshade/MapServer/tile/{z}/{y}/{x}",
        title="Preset Layer URL",
    )
    opacity: confloat(ge=0.0, le=1.0) | None = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class BaseMaps6(BaseModel):
    url: (
        constr(
            pattern=r"https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}([-a-zA-Z0-9()@:%_\+.~#?&//=\{\}]*)"
        )
        | None
    ) = Field(
        "https://example.tiles.com/{z}/{x}/{y}.png",
        description="The URL of a publicly accessible tiled raster service.",
        title="Custom Layer URL",
    )
    opacity: confloat(ge=0.0, le=1.0) | None = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Custom Layer Opacity",
    )
    max_zoom: int | None = Field(
        None,
        description="Set the maximum zoom level to fetch tiles for.",
        title="Custom Layer Max Zoom",
    )
    min_zoom: int | None = Field(
        None,
        description="Set the minimum zoom level to fetch tiles for.",
        title="Custom Layer Min Zoom",
    )


class BaseMapDefs(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    base_maps: (
        list[
            BaseMaps
            | BaseMaps1
            | BaseMaps2
            | BaseMaps3
            | BaseMaps4
            | BaseMaps5
            | BaseMaps6
        ]
        | None
    ) = Field(
        [
            {
                "url": "https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}",
                "opacity": 1,
            },
            {
                "url": "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",
                "opacity": 0.5,
            },
        ],
        description="Select tile layers to use as base layers in map outputs. The first layer in the list will be the bottommost layer displayed.",
        title=" ",
    )


class Filetype(str, Enum):
    csv = "csv"
    gpkg = "gpkg"
    geoparquet = "geoparquet"
    parquet = "parquet"


class PersistSightings(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    filetypes: list[Filetype] | None = Field(
        ["csv"], description="The output format", title="Filetypes"
    )


class WildlifeReport(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    template_path: str = Field(
        ...,
        description="Path or URL to the Word template (.docx) file with Jinja2 placeholders. Supports local paths and remote URLs (http://, https://).",
        title="Template Path",
    )


class TimezoneInfo(BaseModel):
    label: str = Field(..., title="Label")
    tzCode: str = Field(..., title="Tzcode")
    name: str = Field(..., title="Name")
    utc: str = Field(..., title="Utc")


class SMARTConnection(BaseModel):
    name: str = Field(..., title="Data Source")


class BoundingBox(BaseModel):
    min_y: float | None = Field(-90.0, title="Min Latitude")
    max_y: float | None = Field(90.0, title="Max Latitude")
    min_x: float | None = Field(-180.0, title="Min Longitude")
    max_x: float | None = Field(180.0, title="Max Longitude")


class Coordinate(BaseModel):
    y: float = Field(..., description="Example -0.15293", title="Latitude")
    x: float = Field(..., description="Example 37.30906", title="Longitude")


class TimeRange(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    since: datetime = Field(..., description="The start time", title="Since")
    until: datetime = Field(..., description="The end time", title="Until")
    timezone: TimezoneInfo | None = Field(None, title="Timezone")


class SmartClientName(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data_source: SMARTConnection = Field(
        ..., description="Select one of your configured data sources.", title=""
    )


class FilterCoords(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    bounding_box: BoundingBox | None = Field(
        default_factory=lambda: BoundingBox.model_validate(
            {"min_y": -90.0, "max_y": 90.0, "min_x": -180.0, "max_x": 180.0}
        ),
        description="Filter events to inside these bounding coordinates.",
        title="Bounding Box",
    )
    filter_point_coords: list[Coordinate] | None = Field(
        default_factory=list,
        description="By adding a filter, the workflow will not include events recorded at the specified coordinates.",
        title="Filter Exact Point Coordinates",
    )
    roi_gdf: Any | None = Field(
        None,
        description="The ROI geopandas dataframe, in EPSG: 4326, indexed by ROI name",
        title="Roi Gdf",
    )
    roi_name: str | None = Field(None, description="The ROI name", title="Roi Name")
    reset_index: bool | None = Field(
        True, description="Reset index after filtering", title="Reset Index"
    )


class Params(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    workflow_details: WorkflowDetails | None = Field(
        None,
        description="Add information that will help to differentiate this workflow from another.",
        title="Workflow Details",
    )
    time_range: TimeRange | None = Field(
        None, description="Choose the period of time to analyze.", title="Time Range"
    )
    smart_client_name: SmartClientName | None = Field(None, title="Data Source")
    filter_coords: FilterCoords | None = Field(None, title="Filter Coordinates")
    normalize_attrs: NormalizeAttrs | None = Field(
        None, title="Normalize Extracted Attributes"
    )
    featured_list: FeaturedList | None = Field(None, title="Set Featured Species List")
    base_map_defs: BaseMapDefs | None = Field(None, title="Base Maps")
    persist_sightings: PersistSightings | None = Field(
        None, title="Persist Sightings Data"
    )
    wildlife_report: WildlifeReport | None = Field(None, title="Create Wildlife Report")
