# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


# ruff: noqa: E402

# %% [markdown]
# # Mt Wildlife
# TODO: top level description

# %% [markdown]
# ## Imports

import os

from ecoscope_workflows_core.tasks.config import (
    set_list_of_string_vars as set_list_of_string_vars,
)
from ecoscope_workflows_core.tasks.config import set_string_var as set_string_var
from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import (
    get_timezone_from_time_range as get_timezone_from_time_range,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.groupby import set_groupers as set_groupers
from ecoscope_workflows_core.tasks.groupby import split_groups as split_groups
from ecoscope_workflows_core.tasks.io import persist_text as persist_text
from ecoscope_workflows_core.tasks.io import (
    set_smart_connection as set_smart_connection,
)
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_core.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope_workflows_core.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_core.tasks.skip import never as never
from ecoscope_workflows_core.tasks.transformation import (
    convert_values_to_timezone as convert_values_to_timezone,
)
from ecoscope_workflows_ext_custom.tasks.io import (
    persist_df_wrapper as persist_df_wrapper,
)
from ecoscope_workflows_ext_custom.tasks.results import create_docx as create_docx
from ecoscope_workflows_ext_custom.tasks.transformation import (
    apply_sql_query as apply_sql_query,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    exclude_row_values as exclude_row_values,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    filter_row_values as filter_row_values,
)
from ecoscope_workflows_ext_ecoscope.tasks.analysis import summarize_df as summarize_df
from ecoscope_workflows_ext_ecoscope.tasks.io import (
    get_events_from_smart as get_events_from_smart,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import (
    create_point_layer as create_point_layer,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import draw_ecomap as draw_ecomap
from ecoscope_workflows_ext_ecoscope.tasks.results import set_base_maps as set_base_maps
from ecoscope_workflows_ext_ecoscope.tasks.skip import (
    all_geometry_are_none as all_geometry_are_none,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    apply_color_map as apply_color_map,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    apply_reloc_coord_filter as apply_reloc_coord_filter,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    normalize_json_column as normalize_json_column,
)

# %% [markdown]
# ## Workflow Details

# %%
# parameters

workflow_details_params = dict(
    name=...,
    description=...,
    image_url=...,
)

# %%
# call the task


workflow_details = (
    set_workflow_details.set_task_instance_id("workflow_details")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**workflow_details_params)
    .call()
)


# %% [markdown]
# ## Time Range

# %%
# parameters

time_range_params = dict(
    since=...,
    until=...,
    timezone=...,
)

# %%
# call the task


time_range = (
    set_time_range.set_task_instance_id("time_range")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(time_format="%d %b %Y %H:%M:%S %Z", **time_range_params)
    .call()
)


# %% [markdown]
# ## Extract Timezone

# %%
# parameters

get_timezone_params = dict()

# %%
# call the task


get_timezone = (
    get_timezone_from_time_range.set_task_instance_id("get_timezone")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(time_range=time_range, **get_timezone_params)
    .call()
)


# %% [markdown]
# ## Data Source

# %%
# parameters

smart_client_name_params = dict(
    data_source=...,
)

# %%
# call the task


smart_client_name = (
    set_smart_connection.set_task_instance_id("smart_client_name")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**smart_client_name_params)
    .call()
)


# %% [markdown]
# ## Get SMART Events

# %%
# parameters

smart_events_params = dict()

# %%
# call the task


smart_events = (
    get_events_from_smart.set_task_instance_id("smart_events")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        client=smart_client_name,
        time_range=time_range,
        ca_uuid="735606d2-c34e-49c3-a45b-7496ca834e58",
        language_uuid="13451893-86af-4ec0-beac-2b8e0c2482b5",
        **smart_events_params,
    )
    .call()
)


# %% [markdown]
# ## Convert to Timezone

# %%
# parameters

convert_tz_params = dict()

# %%
# call the task


convert_tz = (
    convert_values_to_timezone.set_task_instance_id("convert_tz")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=smart_events, timezone=get_timezone, columns=["time"], **convert_tz_params
    )
    .call()
)


# %% [markdown]
# ## Filter Coordinates

# %%
# parameters

filter_coords_params = dict(
    bounding_box=...,
    filter_point_coords=...,
    roi_name=...,
    reset_index=...,
)

# %%
# call the task


filter_coords = (
    apply_reloc_coord_filter.set_task_instance_id("filter_coords")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(df=convert_tz, roi_gdf=None, **filter_coords_params)
    .call()
)


# %% [markdown]
# ## Normalize Extracted Attributes

# %%
# parameters

normalize_attrs_params = dict()

# %%
# call the task


normalize_attrs = (
    normalize_json_column.set_task_instance_id("normalize_attrs")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=filter_coords,
        column="extracted_attributes",
        skip_if_not_exists=True,
        sort_columns=True,
        **normalize_attrs_params,
    )
    .call()
)


# %% [markdown]
# ## Process Sighting Columns

# %%
# parameters

process_sightings_params = dict()

# %%
# call the task


process_sightings = (
    apply_sql_query.set_task_instance_id("process_sightings")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=normalize_attrs,
        columns=[
            "uuid",
            "event_type",
            "X",
            "Y",
            "time",
            "geometry",
            "extracted_attributes__Species",
            "extracted_attributes__Number of Wildlife observed",
        ],
        query='SELECT uuid, X, Y, time, geometry,\n  "extracted_attributes__Species" AS "Species",\n  COALESCE(CAST("extracted_attributes__Number of Wildlife observed" AS REAL), 0) AS "Count"\nFROM df WHERE event_type = \'Wildlife - direct observation\'\n  AND "extracted_attributes__Species" IS NOT NULL',
        **process_sightings_params,
    )
    .call()
)


# %% [markdown]
# ## Apply Colormap

# %%
# parameters

sightings_colormap_params = dict()

# %%
# call the task


sightings_colormap = (
    apply_color_map.set_task_instance_id("sightings_colormap")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=process_sightings,
        input_column_name="Species",
        output_column_name="species_colormap",
        colormap="Dark2",
        **sightings_colormap_params,
    )
    .call()
)


# %% [markdown]
# ## Set Featured Species List

# %%
# parameters

featured_list_params = dict(
    vars=...,
)

# %%
# call the task


featured_list = (
    set_list_of_string_vars.set_task_instance_id("featured_list")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**featured_list_params)
    .call()
)


# %% [markdown]
# ## Filter Featured Species

# %%
# parameters

featured_species_params = dict()

# %%
# call the task


featured_species = (
    filter_row_values.set_task_instance_id("featured_species")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=sightings_colormap,
        column="Species",
        values=featured_list,
        **featured_species_params,
    )
    .call()
)


# %% [markdown]
# ## Filter Other Species

# %%
# parameters

other_species_params = dict()

# %%
# call the task


other_species = (
    exclude_row_values.set_task_instance_id("other_species")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=sightings_colormap,
        column="Species",
        values=featured_list,
        **other_species_params,
    )
    .call()
)


# %% [markdown]
# ## Summarize Wildlife Sightings

# %%
# parameters

wildlife_summary_params = dict()

# %%
# call the task


wildlife_summary = (
    summarize_df.set_task_instance_id("wildlife_summary")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=process_sightings,
        groupby_cols=["Species"],
        reset_index=False,
        summary_params=[
            {
                "display_name": "Sightings Count",
                "aggregator": "count",
                "column": "Count",
            },
            {
                "display_name": "Individuals Count",
                "aggregator": "sum",
                "column": "Count",
            },
        ],
        **wildlife_summary_params,
    )
    .call()
)


# %% [markdown]
# ## Persist Summary

# %%
# parameters

persist_summary_params = dict(
    filename=...,
)

# %%
# call the task


persist_summary = (
    persist_df_wrapper.set_task_instance_id("persist_summary")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(
        df=wildlife_summary,
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_prefix="wildlife_summary",
        filetypes=["csv"],
        sanitize=False,
        **persist_summary_params,
    )
    .call()
)


# %% [markdown]
# ## Base Maps

# %%
# parameters

base_map_defs_params = dict(
    base_maps=...,
)

# %%
# call the task


base_map_defs = (
    set_base_maps.set_task_instance_id("base_map_defs")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**base_map_defs_params)
    .call()
)


# %% [markdown]
# ## Species Groupers

# %%
# parameters

species_groupers_params = dict()

# %%
# call the task


species_groupers = (
    set_groupers.set_task_instance_id("species_groupers")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(groupers=[{"index_name": "Species"}], **species_groupers_params)
    .call()
)


# %% [markdown]
# ## Split by Species

# %%
# parameters

split_species_params = dict()

# %%
# call the task


split_species = (
    split_groups.set_task_instance_id("split_species")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(df=featured_species, groupers=species_groupers, **split_species_params)
    .call()
)


# %% [markdown]
# ## Featured Map Title

# %%
# parameters

set_featured_title_params = dict()

# %%
# call the task


set_featured_title = (
    set_string_var.set_task_instance_id("set_featured_title")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(var="Wildlife Sightings", **set_featured_title_params)
    .call()
)


# %% [markdown]
# ## Create Featured Point Layers

# %%
# parameters

featured_point_layers_params = dict(
    zoom=...,
)

# %%
# call the task


featured_point_layers = (
    create_point_layer.set_task_instance_id("featured_point_layers")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
            all_geometry_are_none,
        ],
        unpack_depth=1,
    )
    .partial(
        layer_style={"get_radius": 5.0, "fill_color_column": "species_colormap"},
        legend={"label_column": "Species", "color_column": "species_colormap"},
        tooltip_columns=None,
        **featured_point_layers_params,
    )
    .mapvalues(argnames=["geodataframe"], argvalues=split_species)
)


# %% [markdown]
# ## Draw Featured Ecomaps

# %%
# parameters

featured_ecomap_params = dict(
    view_state=...,
    widget_id=...,
)

# %%
# call the task


featured_ecomap = (
    draw_ecomap.set_task_instance_id("featured_ecomap")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        tile_layers=base_map_defs,
        north_arrow_style={"placement": "top-left"},
        legend_style={
            "title": "Species",
            "format_title": True,
            "placement": "bottom-right",
        },
        static=False,
        title=None,
        max_zoom=13,
        **featured_ecomap_params,
    )
    .mapvalues(argnames=["geo_layers"], argvalues=featured_point_layers)
)


# %% [markdown]
# ## Persist Featured Ecomaps

# %%
# parameters

featured_ecomap_html_params = dict(
    filename=...,
)

# %%
# call the task


featured_ecomap_html = (
    persist_text.set_task_instance_id("featured_ecomap_html")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="species_map",
        **featured_ecomap_html_params,
    )
    .mapvalues(argnames=["text"], argvalues=featured_ecomap)
)


# %% [markdown]
# ## Create Other Point Layer

# %%
# parameters

other_point_layer_params = dict(
    zoom=...,
)

# %%
# call the task


other_point_layer = (
    create_point_layer.set_task_instance_id("other_point_layer")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
            all_geometry_are_none,
        ],
        unpack_depth=1,
    )
    .partial(
        geodataframe=other_species,
        layer_style={"get_radius": 5.0, "fill_color_column": "species_colormap"},
        legend={"label_column": "Species", "color_column": "species_colormap"},
        tooltip_columns=None,
        **other_point_layer_params,
    )
    .call()
)


# %% [markdown]
# ## Other Map Title

# %%
# parameters

set_other_title_params = dict()

# %%
# call the task


set_other_title = (
    set_string_var.set_task_instance_id("set_other_title")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(var="Wildlife Sightings - Other Species", **set_other_title_params)
    .call()
)


# %% [markdown]
# ## Draw Other Ecomap

# %%
# parameters

other_ecomap_params = dict(
    view_state=...,
    widget_id=...,
)

# %%
# call the task


other_ecomap = (
    draw_ecomap.set_task_instance_id("other_ecomap")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        geo_layers=other_point_layer,
        tile_layers=base_map_defs,
        north_arrow_style={"placement": "top-left"},
        legend_style={
            "title": "Species",
            "format_title": True,
            "placement": "bottom-right",
        },
        static=False,
        title=None,
        max_zoom=13,
        **other_ecomap_params,
    )
    .call()
)


# %% [markdown]
# ## Persist Other Ecomap

# %%
# parameters

other_ecomap_html_params = dict(
    filename=...,
)

# %%
# call the task


other_ecomap_html = (
    persist_text.set_task_instance_id("other_ecomap_html")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        text=other_ecomap,
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="other_species_map",
        **other_ecomap_html_params,
    )
    .call()
)


# %% [markdown]
# ## Persist Sightings Data

# %%
# parameters

persist_sightings_params = dict(
    filename=...,
    filetypes=...,
)

# %%
# call the task


persist_sightings = (
    persist_df_wrapper.set_task_instance_id("persist_sightings")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(
        df=process_sightings,
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_prefix="wildlife_sightings",
        sanitize=True,
        **persist_sightings_params,
    )
    .call()
)


# %% [markdown]
# ## Report Groupers

# %%
# parameters

report_groupers_params = dict()

# %%
# call the task


report_groupers = (
    set_groupers.set_task_instance_id("report_groupers")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(groupers=[{"index_name": "Species"}], **report_groupers_params)
    .call()
)


# %% [markdown]
# ## Create Wildlife Report

# %%
# parameters

wildlife_report_params = dict(
    template_path=...,
)

# %%
# call the task


wildlife_report = (
    create_docx.set_task_instance_id("wildlife_report")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(
        context={
            "items": [
                {
                    "item_type": "timerange",
                    "key": "report_date",
                    "value": time_range,
                    "format": "%b %Y",
                },
                {"item_type": "table", "key": "summary", "value": wildlife_summary},
                {
                    "item_type": "image",
                    "key": "species_maps",
                    "value": featured_ecomap_html,
                    "include_column_name_in_title": False,
                    "screenshot_config": {
                        "wait_for_timeout": 1000,
                        "max_concurrent_pages": 2,
                        "device_scale_factor": 1.0,
                    },
                },
                {
                    "item_type": "image",
                    "key": "other_map",
                    "value": other_ecomap_html,
                    "screenshot_config": {
                        "wait_for_timeout": 1000,
                        "max_concurrent_pages": 2,
                    },
                },
            ]
        },
        groupers=report_groupers,
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_prefix="mt_wildlife_report",
        **wildlife_report_params,
    )
    .call()
)


# %% [markdown]
# ## Create Dashboard

# %%
# parameters

dashboard_params = dict(
    warning=...,
)

# %%
# call the task


dashboard = (
    gather_dashboard.set_task_instance_id("dashboard")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        details=workflow_details,
        widgets=[],
        groupers=[{"index_name": "Species"}],
        time_range=time_range,
        **dashboard_params,
    )
    .call()
)
