# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details

# ruff: noqa: E402

"""WARNING: This file is generated in a testing context and should not be used in production.
Lines specific to the testing context are marked with a test tube emoji (🧪) to indicate
that they would not be included (or would be different) in the production version of this file.
"""

import json
import os
import warnings  # 🧪

from ecoscope_workflows_core.graph import DependsOn, Graph, Node
from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import (
    get_timezone_from_time_range as get_timezone_from_time_range,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.io import (
    set_smart_connection as set_smart_connection,
)
from ecoscope_workflows_core.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope_workflows_core.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_core.testing import create_task_magicmock  # 🧪

get_events_from_smart = create_task_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_ecoscope.tasks.io",  # 🧪
    func_name="get_events_from_smart",  # 🧪
)  # 🧪
from ecoscope_workflows_core.tasks.config import (
    set_list_of_string_vars as set_list_of_string_vars,
)
from ecoscope_workflows_core.tasks.config import set_string_var as set_string_var
from ecoscope_workflows_core.tasks.groupby import set_groupers as set_groupers
from ecoscope_workflows_core.tasks.groupby import split_groups as split_groups
from ecoscope_workflows_core.tasks.io import persist_text as persist_text
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_core.tasks.skip import never as never
from ecoscope_workflows_core.tasks.transformation import (
    convert_values_to_timezone as convert_values_to_timezone,
)
from ecoscope_workflows_ext_custom.tasks.io import (
    persist_df_wrapper as persist_df_wrapper,
)
from ecoscope_workflows_ext_custom.tasks.results import create_docx as create_docx
from ecoscope_workflows_ext_custom.tasks.transformation import (
    apply_sql_query as apply_sql_query,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    exclude_row_values as exclude_row_values,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    filter_row_values as filter_row_values,
)
from ecoscope_workflows_ext_ecoscope.tasks.analysis import summarize_df as summarize_df
from ecoscope_workflows_ext_ecoscope.tasks.results import (
    create_point_layer as create_point_layer,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import draw_ecomap as draw_ecomap
from ecoscope_workflows_ext_ecoscope.tasks.results import set_base_maps as set_base_maps
from ecoscope_workflows_ext_ecoscope.tasks.skip import (
    all_geometry_are_none as all_geometry_are_none,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    apply_color_map as apply_color_map,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    apply_reloc_coord_filter as apply_reloc_coord_filter,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    normalize_json_column as normalize_json_column,
)

from ..params import Params


def main(params: Params):
    warnings.warn("This test script should not be used in production!")  # 🧪

    params_dict = json.loads(params.model_dump_json(exclude_unset=True))

    dependencies = {
        "workflow_details": [],
        "time_range": [],
        "get_timezone": ["time_range"],
        "smart_client_name": [],
        "smart_events": ["smart_client_name", "time_range"],
        "convert_tz": ["smart_events", "get_timezone"],
        "filter_coords": ["convert_tz"],
        "normalize_attrs": ["filter_coords"],
        "process_sightings": ["normalize_attrs"],
        "sightings_colormap": ["process_sightings"],
        "featured_list": [],
        "featured_species": ["sightings_colormap", "featured_list"],
        "other_species": ["sightings_colormap", "featured_list"],
        "wildlife_summary": ["process_sightings"],
        "persist_summary": ["wildlife_summary"],
        "base_map_defs": [],
        "species_groupers": [],
        "split_species": ["featured_species", "species_groupers"],
        "set_featured_title": [],
        "featured_point_layers": ["split_species"],
        "featured_ecomap": ["base_map_defs", "featured_point_layers"],
        "featured_ecomap_html": ["featured_ecomap"],
        "other_point_layer": ["other_species"],
        "set_other_title": [],
        "other_ecomap": ["other_point_layer", "base_map_defs"],
        "other_ecomap_html": ["other_ecomap"],
        "persist_sightings": ["process_sightings"],
        "report_groupers": [],
        "wildlife_report": [
            "time_range",
            "wildlife_summary",
            "featured_ecomap_html",
            "other_ecomap_html",
            "report_groupers",
        ],
        "dashboard": ["workflow_details", "time_range"],
    }

    nodes = {
        "workflow_details": Node(
            async_task=set_workflow_details.validate()
            .set_task_instance_id("workflow_details")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("workflow_details") or {}),
            method="call",
        ),
        "time_range": Node(
            async_task=set_time_range.validate()
            .set_task_instance_id("time_range")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "time_format": "%d %b %Y %H:%M:%S %Z",
            }
            | (params_dict.get("time_range") or {}),
            method="call",
        ),
        "get_timezone": Node(
            async_task=get_timezone_from_time_range.validate()
            .set_task_instance_id("get_timezone")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "time_range": DependsOn("time_range"),
            }
            | (params_dict.get("get_timezone") or {}),
            method="call",
        ),
        "smart_client_name": Node(
            async_task=set_smart_connection.validate()
            .set_task_instance_id("smart_client_name")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("smart_client_name") or {}),
            method="call",
        ),
        "smart_events": Node(
            async_task=get_events_from_smart.validate()
            .set_task_instance_id("smart_events")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "client": DependsOn("smart_client_name"),
                "time_range": DependsOn("time_range"),
                "ca_uuid": "735606d2-c34e-49c3-a45b-7496ca834e58",
                "language_uuid": "13451893-86af-4ec0-beac-2b8e0c2482b5",
            }
            | (params_dict.get("smart_events") or {}),
            method="call",
        ),
        "convert_tz": Node(
            async_task=convert_values_to_timezone.validate()
            .set_task_instance_id("convert_tz")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("smart_events"),
                "timezone": DependsOn("get_timezone"),
                "columns": [
                    "time",
                ],
            }
            | (params_dict.get("convert_tz") or {}),
            method="call",
        ),
        "filter_coords": Node(
            async_task=apply_reloc_coord_filter.validate()
            .set_task_instance_id("filter_coords")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("convert_tz"),
                "roi_gdf": None,
                "roi_name": None,
                "reset_index": False,
            }
            | (params_dict.get("filter_coords") or {}),
            method="call",
        ),
        "normalize_attrs": Node(
            async_task=normalize_json_column.validate()
            .set_task_instance_id("normalize_attrs")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("filter_coords"),
                "column": "extracted_attributes",
                "skip_if_not_exists": True,
                "sort_columns": True,
            }
            | (params_dict.get("normalize_attrs") or {}),
            method="call",
        ),
        "process_sightings": Node(
            async_task=apply_sql_query.validate()
            .set_task_instance_id("process_sightings")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("normalize_attrs"),
                "columns": [
                    "uuid",
                    "event_type",
                    "X",
                    "Y",
                    "time",
                    "geometry",
                    "extracted_attributes__Species",
                    "extracted_attributes__Number of Wildlife observed",
                ],
                "query": 'SELECT uuid, X, Y, time, geometry,\n  "extracted_attributes__Species" AS "Species",\n  COALESCE(CAST("extracted_attributes__Number of Wildlife observed" AS REAL), 0) AS "Count"\nFROM df WHERE event_type = \'Wildlife - direct observation\'\n  AND "extracted_attributes__Species" IS NOT NULL',
            }
            | (params_dict.get("process_sightings") or {}),
            method="call",
        ),
        "sightings_colormap": Node(
            async_task=apply_color_map.validate()
            .set_task_instance_id("sightings_colormap")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("process_sightings"),
                "input_column_name": "Species",
                "output_column_name": "species_colormap",
                "colormap": "Dark2",
            }
            | (params_dict.get("sightings_colormap") or {}),
            method="call",
        ),
        "featured_list": Node(
            async_task=set_list_of_string_vars.validate()
            .set_task_instance_id("featured_list")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("featured_list") or {}),
            method="call",
        ),
        "featured_species": Node(
            async_task=filter_row_values.validate()
            .set_task_instance_id("featured_species")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("sightings_colormap"),
                "column": "Species",
                "values": DependsOn("featured_list"),
            }
            | (params_dict.get("featured_species") or {}),
            method="call",
        ),
        "other_species": Node(
            async_task=exclude_row_values.validate()
            .set_task_instance_id("other_species")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("sightings_colormap"),
                "column": "Species",
                "values": DependsOn("featured_list"),
            }
            | (params_dict.get("other_species") or {}),
            method="call",
        ),
        "wildlife_summary": Node(
            async_task=summarize_df.validate()
            .set_task_instance_id("wildlife_summary")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("process_sightings"),
                "groupby_cols": [
                    "Species",
                ],
                "reset_index": False,
                "summary_params": [
                    {
                        "display_name": "Sightings Count",
                        "aggregator": "count",
                        "column": "Count",
                    },
                    {
                        "display_name": "Individuals Count",
                        "aggregator": "sum",
                        "column": "Count",
                    },
                ],
            }
            | (params_dict.get("wildlife_summary") or {}),
            method="call",
        ),
        "persist_summary": Node(
            async_task=persist_df_wrapper.validate()
            .set_task_instance_id("persist_summary")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("wildlife_summary"),
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filename_prefix": "wildlife_summary",
                "filetypes": [
                    "csv",
                ],
                "sanitize": False,
            }
            | (params_dict.get("persist_summary") or {}),
            method="call",
        ),
        "base_map_defs": Node(
            async_task=set_base_maps.validate()
            .set_task_instance_id("base_map_defs")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("base_map_defs") or {}),
            method="call",
        ),
        "species_groupers": Node(
            async_task=set_groupers.validate()
            .set_task_instance_id("species_groupers")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "groupers": [
                    {
                        "index_name": "Species",
                    },
                ],
            }
            | (params_dict.get("species_groupers") or {}),
            method="call",
        ),
        "split_species": Node(
            async_task=split_groups.validate()
            .set_task_instance_id("split_species")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("featured_species"),
                "groupers": DependsOn("species_groupers"),
            }
            | (params_dict.get("split_species") or {}),
            method="call",
        ),
        "set_featured_title": Node(
            async_task=set_string_var.validate()
            .set_task_instance_id("set_featured_title")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "var": "Wildlife Sightings",
            }
            | (params_dict.get("set_featured_title") or {}),
            method="call",
        ),
        "featured_point_layers": Node(
            async_task=create_point_layer.validate()
            .set_task_instance_id("featured_point_layers")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                    all_geometry_are_none,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "layer_style": {
                    "get_radius": 5.0,
                    "fill_color_column": "species_colormap",
                },
                "legend": {
                    "label_column": "Species",
                    "color_column": "species_colormap",
                },
                "tooltip_columns": None,
            }
            | (params_dict.get("featured_point_layers") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["geodataframe"],
                "argvalues": DependsOn("split_species"),
            },
        ),
        "featured_ecomap": Node(
            async_task=draw_ecomap.validate()
            .set_task_instance_id("featured_ecomap")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "tile_layers": DependsOn("base_map_defs"),
                "north_arrow_style": {
                    "placement": "top-left",
                },
                "legend_style": {
                    "title": "Species",
                    "format_title": True,
                    "placement": "bottom-right",
                },
                "static": False,
                "title": None,
                "max_zoom": 13,
            }
            | (params_dict.get("featured_ecomap") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["geo_layers"],
                "argvalues": DependsOn("featured_point_layers"),
            },
        ),
        "featured_ecomap_html": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("featured_ecomap_html")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filename_suffix": "species_map",
            }
            | (params_dict.get("featured_ecomap_html") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["text"],
                "argvalues": DependsOn("featured_ecomap"),
            },
        ),
        "other_point_layer": Node(
            async_task=create_point_layer.validate()
            .set_task_instance_id("other_point_layer")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                    all_geometry_are_none,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "geodataframe": DependsOn("other_species"),
                "layer_style": {
                    "get_radius": 5.0,
                    "fill_color_column": "species_colormap",
                },
                "legend": {
                    "label_column": "Species",
                    "color_column": "species_colormap",
                },
                "tooltip_columns": None,
            }
            | (params_dict.get("other_point_layer") or {}),
            method="call",
        ),
        "set_other_title": Node(
            async_task=set_string_var.validate()
            .set_task_instance_id("set_other_title")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "var": "Wildlife Sightings - Other Species",
            }
            | (params_dict.get("set_other_title") or {}),
            method="call",
        ),
        "other_ecomap": Node(
            async_task=draw_ecomap.validate()
            .set_task_instance_id("other_ecomap")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "geo_layers": DependsOn("other_point_layer"),
                "tile_layers": DependsOn("base_map_defs"),
                "north_arrow_style": {
                    "placement": "top-left",
                },
                "legend_style": {
                    "title": "Species",
                    "format_title": True,
                    "placement": "bottom-right",
                },
                "static": False,
                "title": None,
                "max_zoom": 13,
            }
            | (params_dict.get("other_ecomap") or {}),
            method="call",
        ),
        "other_ecomap_html": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("other_ecomap_html")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "text": DependsOn("other_ecomap"),
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filename_suffix": "other_species_map",
            }
            | (params_dict.get("other_ecomap_html") or {}),
            method="call",
        ),
        "persist_sightings": Node(
            async_task=persist_df_wrapper.validate()
            .set_task_instance_id("persist_sightings")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("process_sightings"),
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filename_prefix": "wildlife_sightings",
                "sanitize": True,
            }
            | (params_dict.get("persist_sightings") or {}),
            method="call",
        ),
        "report_groupers": Node(
            async_task=set_groupers.validate()
            .set_task_instance_id("report_groupers")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "groupers": [
                    {
                        "index_name": "Species",
                    },
                ],
            }
            | (params_dict.get("report_groupers") or {}),
            method="call",
        ),
        "wildlife_report": Node(
            async_task=create_docx.validate()
            .set_task_instance_id("wildlife_report")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "context": {
                    "items": [
                        {
                            "item_type": "timerange",
                            "key": "report_date",
                            "value": DependsOn("time_range"),
                            "format": "%b %Y",
                        },
                        {
                            "item_type": "table",
                            "key": "summary",
                            "value": DependsOn("wildlife_summary"),
                        },
                        {
                            "item_type": "image",
                            "key": "species_maps",
                            "value": DependsOn("featured_ecomap_html"),
                            "include_column_name_in_title": False,
                            "screenshot_config": {
                                "wait_for_timeout": 1000,
                                "max_concurrent_pages": 2,
                                "device_scale_factor": 1.0,
                            },
                        },
                        {
                            "item_type": "image",
                            "key": "other_map",
                            "value": DependsOn("other_ecomap_html"),
                            "screenshot_config": {
                                "wait_for_timeout": 1000,
                                "max_concurrent_pages": 2,
                            },
                        },
                    ],
                },
                "groupers": DependsOn("report_groupers"),
                "output_dir": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filename_prefix": "mt_wildlife_report",
            }
            | (params_dict.get("wildlife_report") or {}),
            method="call",
        ),
        "dashboard": Node(
            async_task=gather_dashboard.validate()
            .set_task_instance_id("dashboard")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "details": DependsOn("workflow_details"),
                "groupers": [
                    {
                        "index_name": "Species",
                    },
                ],
                "time_range": DependsOn("time_range"),
            }
            | (params_dict.get("dashboard") or {}),
            method="call",
        ),
    }
    graph = Graph(dependencies=dependencies, nodes=nodes)
    results = graph.execute()
    return results
