# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


"""WARNING: This file is generated in a testing context and should not be used in production.
Lines specific to the testing context are marked with a test tube emoji (🧪) to indicate
that they would not be included (or would be different) in the production version of this file.
"""

import os
import warnings  # 🧪
from typing import Any

from ecoscope.platform.tasks.config import set_workflow_details as set_workflow_details
from ecoscope.platform.tasks.filter import (
    get_timezone_from_time_range as get_timezone_from_time_range,
)
from ecoscope.platform.tasks.filter import set_time_range as set_time_range
from ecoscope.platform.tasks.io import set_er_connection as set_er_connection
from ecoscope.platform.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope.platform.tasks.skip import any_is_empty_df as any_is_empty_df
from wt_contracts import validate as _validate
from wt_task import task
from wt_task.testing import create_func_magicmock  # 🧪

from .. import metadata as _metadata

get_events = create_func_magicmock(  # 🧪
    anchor="ecoscope.platform.tasks.io",  # 🧪
    func_name="get_events",  # 🧪
)  # 🧪
from ecoscope.platform.tasks.transformation import (
    convert_values_to_timezone as convert_values_to_timezone,
)

process_events_details = create_func_magicmock(  # 🧪
    anchor="ecoscope.platform.tasks.io",  # 🧪
    func_name="process_events_details",  # 🧪
)  # 🧪
from ecoscope.platform.tasks.analysis import summarize_df as summarize_df
from ecoscope.platform.tasks.config import (
    set_list_of_string_vars as set_list_of_string_vars,
)
from ecoscope.platform.tasks.config import set_string_var as set_string_var
from ecoscope.platform.tasks.groupby import set_groupers as set_groupers
from ecoscope.platform.tasks.groupby import split_groups as split_groups
from ecoscope.platform.tasks.io import persist_df_wrapper as persist_df_wrapper
from ecoscope.platform.tasks.io import persist_text as persist_text
from ecoscope.platform.tasks.results import create_point_layer as create_point_layer
from ecoscope.platform.tasks.results import draw_ecomap as draw_ecomap
from ecoscope.platform.tasks.results import gather_dashboard as gather_dashboard
from ecoscope.platform.tasks.results import set_base_maps as set_base_maps
from ecoscope.platform.tasks.skip import all_geometry_are_none as all_geometry_are_none
from ecoscope.platform.tasks.skip import never as never
from ecoscope.platform.tasks.transformation import apply_color_map as apply_color_map
from ecoscope.platform.tasks.transformation import (
    apply_reloc_coord_filter as apply_reloc_coord_filter,
)
from ecoscope.platform.tasks.transformation import apply_sql_query as apply_sql_query
from ecoscope.platform.tasks.transformation import (
    drop_column_prefix as drop_column_prefix,
)
from ecoscope.platform.tasks.transformation import (
    normalize_json_column as normalize_json_column,
)
from ecoscope_workflows_ext_custom.tasks.results import create_docx as create_docx
from ecoscope_workflows_ext_custom.tasks.transformation import (
    exclude_row_values as exclude_row_values,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    filter_row_values as filter_row_values,
)


def main(params: dict[str, Any], validate_params_schema: bool = True):
    warnings.warn("This test script should not be used in production!")  # 🧪

    if validate_params_schema:
        _validate(params, _metadata.load_params_schema())

    workflow_details = (
        task(set_workflow_details)
        .validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("workflow_details") or {}))
        .call()
    )

    time_range = (
        task(set_time_range)
        .validate()
        .set_task_instance_id("time_range")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_format="%d %b %Y %H:%M:%S %Z", **(params.get("time_range") or {}))
        .call()
    )

    get_timezone = (
        task(get_timezone_from_time_range)
        .validate()
        .set_task_instance_id("get_timezone")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_range=time_range, **(params.get("get_timezone") or {}))
        .call()
    )

    er_client_name = (
        task(set_er_connection)
        .validate()
        .set_task_instance_id("er_client_name")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("er_client_name") or {}))
        .call()
    )

    er_events = (
        task(get_events)
        # 🧪 validation omitted for mocked IO task (returns pre-loaded example data)
        .set_task_instance_id("er_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client_name,
            time_range=time_range,
            event_types=["wildlife_sightings"],
            event_columns=None,
            include_null_geometry=False,
            raise_on_empty=False,
            include_details=True,
            include_updates=False,
            include_related_events=False,
            include_display_values=True,
            force_point_geometry=True,
            **(params.get("er_events") or {}),
        )
        .call()
    )

    convert_tz = (
        task(convert_values_to_timezone)
        .validate()
        .set_task_instance_id("convert_tz")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=er_events,
            timezone=get_timezone,
            columns=["time"],
            auto_detect=False,
            **(params.get("convert_tz") or {}),
        )
        .call()
    )

    process_event_details = (
        task(process_events_details)
        # 🧪 validation omitted for mocked IO task (returns pre-loaded example data)
        .set_task_instance_id("process_event_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=convert_tz,
            client=er_client_name,
            map_to_titles=True,
            ordered=True,
            **(params.get("process_event_details") or {}),
        )
        .call()
    )

    normalize_event_details = (
        task(normalize_json_column)
        .validate()
        .set_task_instance_id("normalize_event_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=process_event_details,
            column="event_details",
            skip_if_not_exists=True,
            sort_columns=False,
            **(params.get("normalize_event_details") or {}),
        )
        .call()
    )

    drop_event_details_prefix = (
        task(drop_column_prefix)
        .validate()
        .set_task_instance_id("drop_event_details_prefix")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=normalize_event_details,
            prefix="event_details__",
            duplicate_strategy="suffix",
            **(params.get("drop_event_details_prefix") or {}),
        )
        .call()
    )

    filter_coords = (
        task(apply_reloc_coord_filter)
        .validate()
        .set_task_instance_id("filter_coords")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=drop_event_details_prefix,
            roi_gdf=None,
            roi_name=None,
            reset_index=False,
            bounding_box={
                "min_x": -180.0,
                "max_x": 180.0,
                "min_y": -90.0,
                "max_y": 90.0,
            },
            filter_point_coords=[
                {"x": 180.0, "y": 90.0},
                {"x": 0.0, "y": 0.0},
                {"x": 1.0, "y": 1.0},
            ],
            **(params.get("filter_coords") or {}),
        )
        .call()
    )

    process_sightings = (
        task(apply_sql_query)
        .validate()
        .set_task_instance_id("process_sightings")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=filter_coords,
            columns=None,
            sanitize=True,
            query='SELECT id, serial_number, time, geometry,\n  "Species",\n  COALESCE(CAST("Count" AS REAL), 0) AS "Count"\nFROM df WHERE "Species" IS NOT NULL',
            **(params.get("process_sightings") or {}),
        )
        .call()
    )

    sightings_colormap = (
        task(apply_color_map)
        .validate()
        .set_task_instance_id("sightings_colormap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=process_sightings,
            input_column_name="Species",
            output_column_name="species_colormap",
            colormap="Dark2",
            **(params.get("sightings_colormap") or {}),
        )
        .call()
    )

    featured_list = (
        task(set_list_of_string_vars)
        .validate()
        .set_task_instance_id("featured_list")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("featured_list") or {}))
        .call()
    )

    featured_species = (
        task(filter_row_values)
        .validate()
        .set_task_instance_id("featured_species")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=sightings_colormap,
            column="Species",
            values=featured_list,
            **(params.get("featured_species") or {}),
        )
        .call()
    )

    other_species = (
        task(exclude_row_values)
        .validate()
        .set_task_instance_id("other_species")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=sightings_colormap,
            column="Species",
            values=featured_list,
            **(params.get("other_species") or {}),
        )
        .call()
    )

    wildlife_summary = (
        task(summarize_df)
        .validate()
        .set_task_instance_id("wildlife_summary")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=process_sightings,
            groupby_cols=["Species"],
            reset_index=False,
            summary_params=[
                {
                    "display_name": "Sightings Count",
                    "aggregator": "count",
                    "column": "Count",
                },
                {
                    "display_name": "Individuals Count",
                    "aggregator": "sum",
                    "column": "Count",
                },
            ],
            **(params.get("wildlife_summary") or {}),
        )
        .call()
    )

    persist_summary = (
        task(persist_df_wrapper)
        .validate()
        .set_task_instance_id("persist_summary")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            df=wildlife_summary,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_prefix="wildlife_summary",
            filetypes=["csv"],
            sanitize=False,
            **(params.get("persist_summary") or {}),
        )
        .call()
    )

    base_map_defs = (
        task(set_base_maps)
        .validate()
        .set_task_instance_id("base_map_defs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("base_map_defs") or {}))
        .call()
    )

    species_groupers = (
        task(set_groupers)
        .validate()
        .set_task_instance_id("species_groupers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            groupers=[{"index_name": "Species"}],
            **(params.get("species_groupers") or {}),
        )
        .call()
    )

    split_species = (
        task(split_groups)
        .validate()
        .set_task_instance_id("split_species")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=featured_species,
            groupers=species_groupers,
            **(params.get("split_species") or {}),
        )
        .call()
    )

    set_featured_title = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("set_featured_title")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(var="Wildlife Sightings", **(params.get("set_featured_title") or {}))
        .call()
    )

    featured_point_layers = (
        task(create_point_layer)
        .validate()
        .set_task_instance_id("featured_point_layers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
                all_geometry_are_none,
            ],
            unpack_depth=1,
        )
        .partial(
            layer_style={"get_radius": 5.0, "fill_color_column": "species_colormap"},
            legend={"label_column": "Species", "color_column": "species_colormap"},
            tooltip_columns=None,
            **(params.get("featured_point_layers") or {}),
        )
        .mapvalues(argnames=["geodataframe"], argvalues=split_species)
    )

    featured_ecomap = (
        task(draw_ecomap)
        .validate()
        .set_task_instance_id("featured_ecomap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            tile_layers=base_map_defs,
            north_arrow_style={"placement": "top-left"},
            legend_style={
                "title": "Species",
                "format_title": True,
                "placement": "bottom-right",
            },
            static=False,
            title=None,
            max_zoom=13,
            **(params.get("featured_ecomap") or {}),
        )
        .mapvalues(argnames=["geo_layers"], argvalues=featured_point_layers)
    )

    featured_ecomap_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("featured_ecomap_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="species_map",
            **(params.get("featured_ecomap_html") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=featured_ecomap)
    )

    other_point_layer = (
        task(create_point_layer)
        .validate()
        .set_task_instance_id("other_point_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
                all_geometry_are_none,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframe=other_species,
            layer_style={"get_radius": 5.0, "fill_color_column": "species_colormap"},
            legend={"label_column": "Species", "color_column": "species_colormap"},
            tooltip_columns=None,
            **(params.get("other_point_layer") or {}),
        )
        .call()
    )

    set_other_title = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("set_other_title")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            var="Wildlife Sightings - Other Species",
            **(params.get("set_other_title") or {}),
        )
        .call()
    )

    other_ecomap = (
        task(draw_ecomap)
        .validate()
        .set_task_instance_id("other_ecomap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            geo_layers=other_point_layer,
            tile_layers=base_map_defs,
            north_arrow_style={"placement": "top-left"},
            legend_style={
                "title": "Species",
                "format_title": True,
                "placement": "bottom-right",
            },
            static=False,
            title=None,
            max_zoom=13,
            **(params.get("other_ecomap") or {}),
        )
        .call()
    )

    other_ecomap_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("other_ecomap_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            text=other_ecomap,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="other_species_map",
            **(params.get("other_ecomap_html") or {}),
        )
        .call()
    )

    persist_sightings = (
        task(persist_df_wrapper)
        .validate()
        .set_task_instance_id("persist_sightings")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            df=process_sightings,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_prefix="wildlife_sightings",
            sanitize=True,
            **(params.get("persist_sightings") or {}),
        )
        .call()
    )

    report_groupers = (
        task(set_groupers)
        .validate()
        .set_task_instance_id("report_groupers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            groupers=[{"index_name": "Species"}],
            **(params.get("report_groupers") or {}),
        )
        .call()
    )

    wildlife_report = (
        task(create_docx)
        .validate()
        .set_task_instance_id("wildlife_report")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            context={
                "items": [
                    {
                        "item_type": "timerange",
                        "key": "report_date",
                        "value": time_range,
                        "format": "%b %Y",
                    },
                    {"item_type": "table", "key": "summary", "value": wildlife_summary},
                    {
                        "item_type": "image",
                        "key": "species_maps",
                        "value": featured_ecomap_html,
                        "include_column_name_in_title": False,
                        "screenshot_config": {
                            "wait_for_timeout": 1000,
                            "max_concurrent_pages": 2,
                            "device_scale_factor": 1.0,
                        },
                    },
                    {
                        "item_type": "image",
                        "key": "other_map",
                        "value": other_ecomap_html,
                        "screenshot_config": {
                            "wait_for_timeout": 1000,
                            "max_concurrent_pages": 2,
                        },
                    },
                ]
            },
            groupers=report_groupers,
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_prefix="mt_wildlife_report",
            template_path="https://raw.githubusercontent.com/wildlife-dynamics/mt-wildlife/main/resources/templates/mt_wildlife_report_template.docx",
            skip=False,
            **(params.get("wildlife_report") or {}),
        )
        .call()
    )

    dashboard = (
        task(gather_dashboard)
        .validate()
        .set_task_instance_id("dashboard")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            details=workflow_details,
            widgets=[],
            groupers=[{"index_name": "Species"}],
            time_range=time_range,
            **(params.get("dashboard") or {}),
        )
        .call()
    )

    return dashboard
