# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details
import json
import os

from ecoscope_workflows_core.tasks.config import (
    set_list_of_string_vars as set_list_of_string_vars,
)
from ecoscope_workflows_core.tasks.config import set_string_var as set_string_var
from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import (
    get_timezone_from_time_range as get_timezone_from_time_range,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.groupby import set_groupers as set_groupers
from ecoscope_workflows_core.tasks.groupby import split_groups as split_groups
from ecoscope_workflows_core.tasks.io import persist_text as persist_text
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_core.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope_workflows_core.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_core.tasks.skip import never as never
from ecoscope_workflows_core.tasks.transformation import (
    convert_values_to_timezone as convert_values_to_timezone,
)
from ecoscope_workflows_ext_custom.tasks.io import load_df as load_df
from ecoscope_workflows_ext_custom.tasks.io import (
    persist_df_wrapper as persist_df_wrapper,
)
from ecoscope_workflows_ext_custom.tasks.results import create_docx as create_docx
from ecoscope_workflows_ext_custom.tasks.transformation import (
    apply_sql_query as apply_sql_query,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    exclude_row_values as exclude_row_values,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    filter_row_values as filter_row_values,
)
from ecoscope_workflows_ext_ecoscope.tasks.analysis import summarize_df as summarize_df
from ecoscope_workflows_ext_ecoscope.tasks.results import (
    create_point_layer as create_point_layer,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import draw_ecomap as draw_ecomap
from ecoscope_workflows_ext_ecoscope.tasks.results import set_base_maps as set_base_maps
from ecoscope_workflows_ext_ecoscope.tasks.skip import (
    all_geometry_are_none as all_geometry_are_none,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    apply_color_map as apply_color_map,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    apply_reloc_coord_filter as apply_reloc_coord_filter,
)

from ..params import Params


def main(params: Params):
    params_dict = json.loads(params.model_dump_json(exclude_unset=True))

    workflow_details = (
        set_workflow_details.validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("workflow_details") or {}))
        .call()
    )

    time_range = (
        set_time_range.validate()
        .set_task_instance_id("time_range")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            time_format="%d %b %Y %H:%M:%S %Z", **(params_dict.get("time_range") or {})
        )
        .call()
    )

    get_timezone = (
        get_timezone_from_time_range.validate()
        .set_task_instance_id("get_timezone")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_range=time_range, **(params_dict.get("get_timezone") or {}))
        .call()
    )

    smart_events = (
        load_df.validate()
        .set_task_instance_id("smart_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(deserialize_json=False, **(params_dict.get("smart_events") or {}))
        .call()
    )

    convert_tz = (
        convert_values_to_timezone.validate()
        .set_task_instance_id("convert_tz")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=smart_events,
            timezone=get_timezone,
            columns=["time"],
            **(params_dict.get("convert_tz") or {}),
        )
        .call()
    )

    filter_coords = (
        apply_reloc_coord_filter.validate()
        .set_task_instance_id("filter_coords")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(df=convert_tz, **(params_dict.get("filter_coords") or {}))
        .call()
    )

    process_sightings = (
        apply_sql_query.validate()
        .set_task_instance_id("process_sightings")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=filter_coords,
            columns=None,
            query="SELECT uuid, X, Y, time, geometry,\n  json_extract(extracted_attributes, '$.Species') AS \"Species\",\n  (COALESCE(CAST(json_extract(extracted_attributes, '$.\"Number of Wildlife observed\"') AS REAL), 0)\n  + COALESCE(CAST(json_extract(extracted_attributes, '$.\"Number of Age or Sex Unknown\"') AS REAL), 0)\n  + COALESCE(CAST(json_extract(extracted_attributes, '$.\"Number of Adult Females\"') AS REAL), 0)\n  + COALESCE(CAST(json_extract(extracted_attributes, '$.\"Number of Adult Males\"') AS REAL), 0)\n  + COALESCE(CAST(json_extract(extracted_attributes, '$.\"Number of Young\"') AS REAL), 0))\n  AS \"Count\"\nFROM df WHERE event_type = 'Wildlife - direct observation'\n  AND json_extract(extracted_attributes, '$.Species') IS NOT NULL",
            **(params_dict.get("process_sightings") or {}),
        )
        .call()
    )

    sightings_colormap = (
        apply_color_map.validate()
        .set_task_instance_id("sightings_colormap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=process_sightings,
            input_column_name="Species",
            output_column_name="species_colormap",
            colormap="Dark2",
            **(params_dict.get("sightings_colormap") or {}),
        )
        .call()
    )

    featured_list = (
        set_list_of_string_vars.validate()
        .set_task_instance_id("featured_list")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("featured_list") or {}))
        .call()
    )

    featured_species = (
        filter_row_values.validate()
        .set_task_instance_id("featured_species")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=sightings_colormap,
            column="Species",
            values=featured_list,
            **(params_dict.get("featured_species") or {}),
        )
        .call()
    )

    other_species = (
        exclude_row_values.validate()
        .set_task_instance_id("other_species")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=sightings_colormap,
            column="Species",
            values=featured_list,
            **(params_dict.get("other_species") or {}),
        )
        .call()
    )

    wildlife_summary = (
        summarize_df.validate()
        .set_task_instance_id("wildlife_summary")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=process_sightings,
            groupby_cols=["Species"],
            reset_index=False,
            summary_params=[
                {
                    "display_name": "Sightings Count",
                    "aggregator": "count",
                    "column": "Count",
                },
                {
                    "display_name": "Individuals Count",
                    "aggregator": "sum",
                    "column": "Count",
                },
            ],
            **(params_dict.get("wildlife_summary") or {}),
        )
        .call()
    )

    persist_summary = (
        persist_df_wrapper.validate()
        .set_task_instance_id("persist_summary")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            df=wildlife_summary,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_prefix="wildlife_summary",
            filetypes=["csv"],
            sanitize=False,
            **(params_dict.get("persist_summary") or {}),
        )
        .call()
    )

    base_map_defs = (
        set_base_maps.validate()
        .set_task_instance_id("base_map_defs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("base_map_defs") or {}))
        .call()
    )

    species_groupers = (
        set_groupers.validate()
        .set_task_instance_id("species_groupers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            groupers=[{"index_name": "Species"}],
            **(params_dict.get("species_groupers") or {}),
        )
        .call()
    )

    split_species = (
        split_groups.validate()
        .set_task_instance_id("split_species")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=featured_species,
            groupers=species_groupers,
            **(params_dict.get("split_species") or {}),
        )
        .call()
    )

    set_featured_title = (
        set_string_var.validate()
        .set_task_instance_id("set_featured_title")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            var="Wildlife Sightings", **(params_dict.get("set_featured_title") or {})
        )
        .call()
    )

    featured_point_layers = (
        create_point_layer.validate()
        .set_task_instance_id("featured_point_layers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
                all_geometry_are_none,
            ],
            unpack_depth=1,
        )
        .partial(
            layer_style={"get_radius": 5.0, "fill_color_column": "species_colormap"},
            legend={"label_column": "Species", "color_column": "species_colormap"},
            tooltip_columns=None,
            **(params_dict.get("featured_point_layers") or {}),
        )
        .mapvalues(argnames=["geodataframe"], argvalues=split_species)
    )

    featured_ecomap = (
        draw_ecomap.validate()
        .set_task_instance_id("featured_ecomap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            tile_layers=base_map_defs,
            north_arrow_style={"placement": "top-left"},
            legend_style={
                "title": "Species",
                "format_title": True,
                "placement": "bottom-right",
            },
            static=False,
            title=None,
            max_zoom=13,
            **(params_dict.get("featured_ecomap") or {}),
        )
        .mapvalues(argnames=["geo_layers"], argvalues=featured_point_layers)
    )

    featured_ecomap_html = (
        persist_text.validate()
        .set_task_instance_id("featured_ecomap_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="species_map",
            **(params_dict.get("featured_ecomap_html") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=featured_ecomap)
    )

    other_point_layer = (
        create_point_layer.validate()
        .set_task_instance_id("other_point_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
                all_geometry_are_none,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframe=other_species,
            layer_style={"get_radius": 5.0, "fill_color_column": "species_colormap"},
            legend={"label_column": "Species", "color_column": "species_colormap"},
            tooltip_columns=None,
            **(params_dict.get("other_point_layer") or {}),
        )
        .call()
    )

    set_other_title = (
        set_string_var.validate()
        .set_task_instance_id("set_other_title")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            var="Wildlife Sightings - Other Species",
            **(params_dict.get("set_other_title") or {}),
        )
        .call()
    )

    other_ecomap = (
        draw_ecomap.validate()
        .set_task_instance_id("other_ecomap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            geo_layers=other_point_layer,
            tile_layers=base_map_defs,
            north_arrow_style={"placement": "top-left"},
            legend_style={
                "title": "Species",
                "format_title": True,
                "placement": "bottom-right",
            },
            static=False,
            title=None,
            max_zoom=13,
            **(params_dict.get("other_ecomap") or {}),
        )
        .call()
    )

    other_ecomap_html = (
        persist_text.validate()
        .set_task_instance_id("other_ecomap_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            text=other_ecomap,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="other_species_map",
            **(params_dict.get("other_ecomap_html") or {}),
        )
        .call()
    )

    persist_sightings = (
        persist_df_wrapper.validate()
        .set_task_instance_id("persist_sightings")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            df=process_sightings,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_prefix="wildlife_sightings",
            sanitize=True,
            **(params_dict.get("persist_sightings") or {}),
        )
        .call()
    )

    report_groupers = (
        set_groupers.validate()
        .set_task_instance_id("report_groupers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            groupers=[{"index_name": "Species"}],
            **(params_dict.get("report_groupers") or {}),
        )
        .call()
    )

    wildlife_report = (
        create_docx.validate()
        .set_task_instance_id("wildlife_report")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            context={
                "items": [
                    {
                        "item_type": "timerange",
                        "key": "report_date",
                        "value": time_range,
                        "format": "%b %Y",
                    },
                    {"item_type": "table", "key": "summary", "value": wildlife_summary},
                    {
                        "item_type": "image",
                        "key": "species_maps",
                        "value": featured_ecomap_html,
                        "include_column_name_in_title": False,
                        "screenshot_config": {
                            "wait_for_timeout": 1000,
                            "max_concurrent_pages": 2,
                            "device_scale_factor": 1.0,
                        },
                    },
                    {
                        "item_type": "image",
                        "key": "other_map",
                        "value": other_ecomap_html,
                        "screenshot_config": {
                            "wait_for_timeout": 1000,
                            "max_concurrent_pages": 2,
                        },
                    },
                ]
            },
            groupers=report_groupers,
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_prefix="mt_wildlife_report",
            **(params_dict.get("wildlife_report") or {}),
        )
        .call()
    )

    dashboard = (
        gather_dashboard.validate()
        .set_task_instance_id("dashboard")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            details=workflow_details,
            widgets=[],
            groupers=[{"index_name": "Species"}],
            time_range=time_range,
            **(params_dict.get("dashboard") or {}),
        )
        .call()
    )

    return dashboard
